//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Coursemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Enrolleds = new HashSet<Enrolled>();
            this.Waitlists = new HashSet<Waitlist>();
        }
    
        public string Dept { get; set; }
        public short CourseNum { get; set; }
        public string Semester { get; set; }
        public short Year { get; set; }
        public int CRN { get; set; }
        public string Type { get; set; }
        public string Day { get; set; }
        public string MeetingTime { get; set; }
        public short ClassSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolled> Enrolleds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waitlist> Waitlists { get; set; }
    }
}
